# Generated by Django 5.1.7 on 2025-04-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voucher_no", models.CharField(max_length=20, unique=True)),
                ("registration_plate", models.CharField(max_length=15, unique=True)),
                ("contact_no", models.CharField(max_length=15)),
            ],
        ),
    ]
